ChangeNotifierの実装(トークルームページ)
ProgrammableGroup/chat-flutter pull request #22
Opened 2020-07-20 15:43 UTC by tomoki-inoue1221

# issue
#13 

# やったこと
・room_controllerの作成
・既存のroom.dartをcontrollerで置き換え
・textFieldの切り分け

# 懸念点
・TextEditingControllerをControllerに書き出して、controller経由でTextFieldを実装していますが、
このあたり自信ないので、もし意見あったらください！

2020-07-21 12:02 UTC, thoth000 requested changes
何か所か修正箇所をレビューしました！

2020-07-21 12:02 UTC, thoth000 commented on lib/ui/pages/main/room/room_controller.dart
> +  TextEditingController textController = TextEditingController();
textControllerは変化する値ではない？と思ったので、TextFieldのあるクラスにおいていいと思います。
（textControllerに対して行われる関数は.clearだけなので…）

2020-07-21 12:02 UTC, thoth000 commented on lib/ui/molecules/message/list.dart
>  import 'package:chat_flutter/model/message.dart';
`import 'package:chat_flutter/model/message.dart';`
ここの部分、使われていないので削除していいと思います！

2020-07-21 12:02 UTC, thoth000 commented on lib/ui/pages/main/room/room_controller.dart
> +  }
textControllerをここのクラスに置かないのならば、
textController.textで文字列を受け取って、Firebaseでの処理のみにしたらいいと思います！

2020-07-22 15:07 UTC, thoth000 reviewed
実装部分はこれで問題ないと思います！

2020-07-22 15:07 UTC, thoth000 commented on lib/ui/pages/main/room/room_controller.dart
> +  Future<void> sendMessage(String message) {
ここはFutureなのでasyncつけた方が良いと思います！

2020-07-22 15:11 UTC, thoth000 commented
自分のPR(#16 )のミスのせいなんですが、pages/mainというディレクトリがありますよね。
ここにroomが入ってるのはおかしくて、mainはbottomNavigationで移動できるページをまとめたものなので、
main外にroomディレクトリを移してほしいです！

2020-07-22 15:12 UTC, tomoki-inoue1221 commented on lib/ui/pages/main/room/room_controller.dart
> +  Future<void> sendMessage(String message) {
実装時に必要になるので、firebaseの実装時につけるでもいいですか？

2020-07-22 15:14 UTC, tomoki-inoue1221 commented
ディレクトリを移動するissueを作成して、ログ残すためにもまとめて整理した方がいい気がします！

2020-07-22 15:14 UTC, thoth000 commented on lib/ui/pages/main/room/room_controller.dart
> +  Future<void> sendMessage(String message) {
OKです！

2020-07-22 15:16 UTC, thoth000 approved these changes

2020-07-22 15:18 UTC, merged