プロフィールの編集・更新
ProgrammableGroup/chat-flutter pull request #43
Opened 2020-08-15 10:30 UTC by thoth000

2020-08-16 12:55 UTC, ho2ri2s reviewed
pc手元になくて動作確認できてませんm

2020-08-16 12:55 UTC, ho2ri2s commented on lib/services/auth/authenticator.dart
> +    final authResult = await _firebaseAuth.createUserWithEmailAndPassword(
これはどういう差分だろう？
改行いれるなら、passwordの後に `,` 入れる感じかな？

2020-08-16 12:55 UTC, ho2ri2s commented on lib/services/firebase_user_service.dart
> +    if (imgUrl == '') {
どちらでも良いですが `imgUrl.isEmpty` な書き方を自分はよくします。
あと、imageUrlがnullの場合って考慮する必要ありそうですか？

2020-08-16 12:55 UTC, ho2ri2s commented on lib/services/firebase_user_service.dart
> +    return User(
せっかく `User#formJson` 定義されているので、それ使ってもよいかもですね

2020-08-16 12:55 UTC, ho2ri2s commented on lib/ui/pages/home/home.dart
> +              Provider.of<Authenticator>(context, listen: false)),
ここもfalseのあとにコロンがあると良いかもです。

2020-08-16 12:55 UTC, ho2ri2s commented on lib/ui/pages/profile/profile_controller.dart
> +    getUserById('Kh2FY47Y0kak7zWB9bE7zY7FkCH3');
userIdは、AuthenticatorクラスでFirebaseAuthのインスタンスを取得しているので、
getUIdのようなメソッドをはやして、 firebaseAuth.currentUserから取得すると良いと思います。

2020-08-16 12:55 UTC, ho2ri2s commented on lib/ui/pages/profile/profile_controller.dart
> +    final imagePicker = ImagePicker();
関心の分離の観点で、ImagePickerというViewに近い関心はWidget側に書きたいなと思いました。
`selectedImage` を取得するのはWidget側で行い、 selectProfileImage（命名は変えた方が良いかも）の引数にそれを渡す感じですかね

2020-08-16 12:55 UTC, ho2ri2s commented on lib/ui/pages/profile/profile_controller.dart
> +    final FirebaseStorageService firebaseStorageService =
Authenticatorのように、ProfileControllerの初期化時に引数で渡すようにすると良いかもです。
FirebaseStorageServiceの生存期間はApplicationの生存期間と同じ印象なのでなるべくSingletonに近い挙動にするとバグが起きにくくなるかもしれません

2020-08-16 12:55 UTC, ho2ri2s commented on lib/ui/pages/profile/profile_edit.dart
> +      create: (_) =>
ここも差分がでてますね

2020-08-17 04:52 UTC, thoth000 commented
自分が分かる範囲で、指摘箇所を修正しました。
良く実装方法が分かっていない箇所は
- FirebaseStorageの生存期間を考えた実装
- getUidを使ってuidを取得するまではいいが、constructorでasync,awaitが使えないためgetUidを使えない

というところです。
そこまではcommitしてあるので、教えていただけたらありがたいです。

2020-08-17 13:30 UTC, PictoMki requested changes
プラスでlintの警告が結構出てるので合わせて直してもらえるありがたいです！

2020-08-17 13:30 UTC, tomoki-inoue1221 commented on lib/services/firebase_storage_service.dart
> +    print('Download URL : $url');
print消しちゃって大丈夫だと思います！

2020-08-17 13:30 UTC, tomoki-inoue1221 commented on lib/services/firebase_user_service.dart
> +    await _db.collection('message/v1/users').document('$uid').setData(userData);
ここって'$uid'にしなきゃいけない理由ってなんでしたっけ？

2020-08-17 13:30 UTC, tomoki-inoue1221 commented on lib/ui/pages/profile/profile.dart
> +          ),
この仮IDを置き換えるのは別issueって感じですか？

2020-08-17 13:30 UTC, tomoki-inoue1221 commented on lib/ui/pages/profile/profile_edit.dart
> +        decoration: const BoxDecoration(
この辺profile_image.dartでも同じような書き方がある気がするが、
どっちか使ってない？

2020-08-18 13:56 UTC, thoth000 commented on lib/services/firebase_storage_service.dart
> +    print('Download URL : $url');
はい！

2020-08-18 13:56 UTC, thoth000 commented on lib/services/firebase_user_service.dart
> +    await _db.collection('message/v1/users').document('$uid').setData(userData);
uidっていう変数名だけだとエラーが出まして…

2020-08-18 13:57 UTC, thoth000 commented on lib/ui/pages/profile/profile.dart
> +          ),
自分が出来ないので別PRで切ってもらえると正直自分はありがたいです！

2020-08-18 13:58 UTC, thoth000 commented on lib/ui/pages/profile/profile_edit.dart
> +        decoration: const BoxDecoration(
確かにそうですね！
改善できそうです！

2020-08-18 13:59 UTC, thoth000 commented on lib/ui/pages/profile/profile_controller.dart
> +    getUserById('Kh2FY47Y0kak7zWB9bE7zY7FkCH3');
ここらへんがよく分からず自分では実装できないと思ってるので別PRで直していただけると自分はありがたいです！

2020-08-18 14:00 UTC, thoth000 commented on lib/ui/pages/profile/profile_controller.dart
> +    final imagePicker = ImagePicker();
なるほど…
確かに写真選択のViewが出ますもんね。
そうしたいと思います！

2020-08-20 06:10 UTC, tomoki-inoue1221 commented
今動作確認してみたのですが、
新規会員登録
↓
プロフィールタブに移動
すると、画像のようにnullになってしまいます！
ここだけ修正していただけたら引き継ぐので修正お願いします!
<img src="https://user-images.githubusercontent.com/56622027/90722999-dd3fce80-e2f6-11ea-8aff-cff0983170bb.png" width=300/>
<img src="https://user-images.githubusercontent.com/56622027/90723011-e03abf00-e2f6-11ea-93fc-fad5586edf31.png" width=300/>

2020-08-20 07:58 UTC, tomoki-inoue1221 approved these changes
良さそう！

2020-08-20 08:01 UTC, merged